In [73]:
# np.array (Vector)
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
# 2D(Matrix) and 3D(Tensor) array
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [10]:
# dtype
d = np.array([1,2,3],dtype=float)
print(d)


[1. 2. 3.]


In [12]:
d = np.array([1,2,3,0],dtype=bool)
print(d)

[ True  True  True False]


In [13]:
d = np.array([1,2,3,0],dtype=complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 0.+0.j]


In [17]:
# np.arange

a = np.arange(1, 11)
print(a)
b = np.arange(1, 13, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11]


In [21]:
# np.reshape

a = np.arange(1, 11).reshape(5, 2) #splits into (row, col)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [24]:
# np.ones and np.zeros

a = np.ones((3, 4))
print(a)

print("\n")

b = np.zeros((4,5))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
# np.random

a = np.random.random((3,4))
print(a)

[[0.27531585 0.8218517  0.24179497 0.2222139 ]
 [0.45859234 0.99319453 0.19305346 0.0345935 ]
 [0.66780552 0.68695217 0.58765893 0.37263708]]


In [29]:
# np.linspace (linear space)

a = np.linspace(-10, 10, 10) # (lower range, upper, num of items)
print(a)



[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [32]:
# np.identity (identity matrix)

a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
# array attributes

a1 = np.arange(10,dtype=np.int32) #vector

a2 = np.arange(12, dtype=float).reshape(3,4) #matrix

a3 = np.arange(8).reshape(2,2,2) #tensor

print(a1)
print(a2)
print(a3)



[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [40]:
# ndim (number of dimension)

a1.ndim
a2.ndim
a3.ndim

3

In [44]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [46]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [52]:
#itemsize

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [53]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [ ]:
# Changing Datatype


In [56]:
# astype

a4 = a3.astype(np.int32)
print(a4.dtype)

int32


In [ ]:
# Array Operations

In [60]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print("\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [64]:
# scalar operations

#arithmetic

print(a1 ** 2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [67]:
# relational

print(a2 > 13)

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [69]:
# vector operations

# arithmetic

print(a1 + a2)
print("\n")
print(a1 * a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [ ]:
# Array Functions

In [76]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print("\n")
print(a1)


[[0.96483764 0.1111672  0.67608926]
 [0.1132683  0.85369746 0.34608331]
 [0.97401307 0.11547601 0.78924824]]


[[96. 11. 68.]
 [11. 85. 35.]
 [97. 12. 79.]]


In [84]:
# max/min/sum/product

a = np.max(a1)
b = np.min(a1)
c = np.sum(a1)
d = np.prod(a1)
print(a)
print(b)
print(c)
print(d)

print("\n")

e = np.max(a1, axis=1) # 0 -> col, 1 -> row
print(e)

97.0
11.0
494.0
216088949260800.0


[96. 85. 97.]


In [87]:
# mean/median/std/var

a = np.mean(a1)
print(a)

b = np.median(a1)
print(b)

c = np.std(a1)
print(c)

d = np.var(a1)
print(d)

54.888888888888886
68.0
35.29382836966903
1245.6543209876543


In [88]:
# trigonometric

np.sin(a1)

array([[ 0.98358775, -0.99999021, -0.89792768],
       [-0.99999021, -0.17607562, -0.42818267],
       [ 0.37960774, -0.53657292, -0.44411267]])

In [ ]:
# dot product

a2 = np.arange()